### ISSUE TITLE
Many Features broke in v1.1.13

### ISSUE THREAD

**Issue by pavanjava** [livekit/livekit#4644]
**Describe the bug**
after upgrading from 1.1.12 to 1.1.13 not able to get the `EndCallTool()`, `session.usage` and `session_usage_updated` 

**Server**
- Version: [1.13.2]
- Environment: [local dev]

**Client**
- SDK: [python]
- Version: [1.1.13]

**To Reproduce**
1. local client is connected to room
2. when logging the usage at the time of context shutdown, at the time of agent bootstrap to register `session_usage_updated` event
3. See error

```
Traceback (most recent call last):
  File "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/voice_agents/livekit_course/livekit_observability/agent_with_observability.py", line 6, in <module>
    from livekit.agents import (
ImportError: cannot import name 'SessionUsageUpdatedEvent' from 'livekit.agents' (/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/voice_agents/livekit_course/.venv/lib/python3.12/site-packages/livekit/agents/__init__.py)
```

```
22:49:45.543 ERROR  livekit.agents   error while shutting down the job                                                                                                {"room": "mock_room"}
                                         Traceback (most recent call last):                                                                                                                    
                                           File                                                                                                                                                
                                         "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/voice_agents/livekit_course/.venv/lib/python3.12/site-packages/                      
                                         livekit/agents/ipc/job_proc_lazy_main.py", line 351, in _run_job_task                                                                                 
                                             await asyncio.gather(*shutdown_tasks)                                                                                                             
                                           File                                                                                                                                                
                                         "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/voice_agents/livekit_course/.venv/lib/python3.12/site-packages/                      
                                         livekit/agents/job.py", line 361, in wrapper                                                                                                          
                                             await callback()  # type: ignore                                                                                                                  
                                             ^^^^^^^^^^^^^^^^                                                                                                                                  
                                           File                                                                                                                                                
                                         "/Users/pavanmantha/Pavans/PracticeExamples/DataScience_Practice/voice_agents/livekit_course/livekit_observability/agent_with_ob                      
                                         servability.py", line 88, in log_usage                                                                                                                
                                             for usage in session.usage.model_usage:                                                                                                           
                                                          ^^^^^^^^^^^^^                                                                                                                        
                                         AttributeError: 'AgentSession' object has no attribute 'usage' 
```

**Expected behavior**
all the features like metrics_collected(depricated), session.usage and EndCallTool() should work normal with out any error.

**Screenshots**

<img width="932" height="111" alt="Image" src="https://github.com/user-attachments/assets/58010191-e8ee-48cc-bcb9-85bec559f3c5" />

<img width="604" height="200" alt="Image" src="https://github.com/user-attachments/assets/c2f9d63e-2271-46d2-a975-94325c9f6946" />

**Comment by pavanjava** [comment]
The issue is with a mis matched livekit-agents version i figured and fixed and now everything works normal.
