### ISSUE TITLE
dtls timeout: read/write timeout: context deadline exceeded

### ISSUE THREAD

**Issue by viplifes** [livekit/livekit#4149]
**Describe the bug**
After upgrading LiveKit from 1.9.4 → 1.9.8, we started seeing frequent DTLS/data-channel errors in the server logs. Many participants cannot join rooms or get disconnected during connection attempts. The issue did not exist on 1.9.4.

**Server**
Version: 1.9.8 (working fine on 1.9.4)
Environment: Kubernetes (EKS)
Setup: Standard SFU deployment, auto-scaling, no config changes besides version bump.

**Client**
- SDK: js and flutter

```
2025-12-11T09:26:02.107Z WARN livekit.transport rtc/transport.go:1259 error reading data channel {"room": "352d46bd-8f93-4ccc-b36b-574db173e72e", "roomID": "RM_pvAoa9ekx94m", "participant": "agent-AJ_xsRCGqpk9NAy", "pID": "PA_3buPtSwbTHpn", "remote": false, "transport": "SUBSCRIBER", "label": "_lossy", "error": "dtls timeout: read/write timeout: context deadline exceeded"} 

2025-12-11T09:25:42.004Z WARN livekit.transport rtc/transport.go:1259 error reading data channel {"room": "352d46bd-8f93-4ccc-b36b-574db173e72e", "roomID": "RM_pvAoa9ekx94m", "participant": "61681#chrome-646dcda4-095f-420c-8ecd-084a8809581d", "pID": "PA_VmRuCWMGShS4", "remote": false, "transport": "SUBSCRIBER", "label": "_lossy", "error": "dtls timeout: read/write timeout: context deadline exceeded"} 


2025-12-11T09:19:31.453Z WARN livekit.transport rtc/transport.go:901 error reading data channel {"room": "7481ff88-0216-46e5-a99f-5ff44c221901", "roomID": "RM_dPUxBYJToQEg", "participant": "916370#chrome-333397ac-9393-4225-9325-513473387bd0", "pID": "PA_RytLwFgTL9Hi", "remote": false, "transport": "PUBLISHER", "label": "_lossy", "error": "dtls timeout: read/write timeout: context deadline exceeded"} 


2025-12-11T09:19:17.050Z ERROR livekit service/signal.go:186 could not handle new participant {"room": "7481ff88-0216-46e5-a99f-5ff44c221901", "participant": "65281#b3ab6760-bba8-11f0-816d-77f612c68260", "connID": "CO_R3vYTKmtQ9Ud", "error": "could not restart participant", "errorVerbose": "could not restart participant\ngithub.com/livekit/livekit-server/pkg/service.(*RoomManager).StartSession\n\t/workspace/pkg/service/roommanager.go:400\ngithub.com/livekit/livekit-server/pkg/service.(*defaultSessionHandler).HandleSession\n\t/workspace/pkg/service/signal.go:115\ngithub.com/livekit/livekit-server/pkg/service.(*signalService).RelaySignal\n\t/workspace/pkg/service/signal.go:183\ngithub.com/livekit/psrpc/pkg/server.(*streamHandler[...]).handleOpenRequest\n\t/go/pkg/mod/github.com/livekit/psrpc@v0.7.1/pkg/server/stream.go:202\ngithub.com/livekit/psrpc/pkg/server.(*streamHandler[...]).handleRequest.func1\n\t/go/pkg/mod/github.com/livekit/psrpc@v0.7.1/pkg/server/stream.go:141\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1268"}
```

**Comment by boks1971** [comment]
There was a more spec compliant change with DTLS in v1.9.8.

Are you seeing issues during initial connection or when the participant disconnects and tries to reconnect?

**Comment by viplifes** [comment]
It looks like these errors happen during reconnections, not during the initial join.
From the logs we can see a normal join sequence:
```
2025-12-11T08:30:05.015Z INFO  starting RTC session
2025-12-11T08:30:06.432Z INFO  participant active
2025-12-11T08:30:15.708Z INFO  mediaTrack published

2025-12-11T08:31:05.496Z INFO livekit rtc/participant.go:1345 participant closing {"room": "52341bea-4810-4950-9498-8706c60842ab", "roomID": "RM_8KDAkuUETcRE", "participant": "142601#8751b500-c0c3-11f0-b2ab-998286962dfa", "pID": "PA_h68XTimnMbVU", "remote": false, "sendLeave": true, "reason": "CLIENT_REQUEST_LEAVE", "isExpectedToResume": false}

2025-12-11T08:31:05.497Z WARN livekit.transport rtc/transport.go:901 error reading data channel {"room": "52341bea-4810-4950-9498-8706c60842ab", "roomID": "RM_8KDAkuUETcRE", "participant": "142601#8751b500-c0c3-11f0-b2ab-998286962dfa", "pID": "PA_h68XTimnMbVU", "remote": false, "transport": "PUBLISHER", "label": "_lossy", "error": "dtls timeout: read/write timeout: context deadline exceeded"}


2025-12-11T08:31:05.497Z	WARN	livekit.transport	rtc/transport.go:901	error reading data channel	{"room": "52341bea-4810-4950-9498-8706c60842ab", "roomID": "RM_8KDAkuUETcRE", "participant": "142601#8751b500-c0c3-11f0-b2ab-998286962dfa", "pID": "PA_h68XTimnMbVU", "remote": false, "transport": "PUBLISHER", "label": "_reliable", "error": "dtls timeout: read/write timeout: context deadline exceeded"}


2025-12-11T08:31:05.497Z	WARN	livekit.transport	rtc/transport.go:1259	error reading data channel	{"room": "52341bea-4810-4950-9498-8706c60842ab", "roomID": "RM_8KDAkuUETcRE", "participant": "142601#8751b500-c0c3-11f0-b2ab-998286962dfa", "pID": "PA_h68XTimnMbVU", "remote": false, "transport": "SUBSCRIBER", "label": "_reliable", "error": "dtls timeout: read/write timeout: context deadline exceeded"}


2025-12-11T08:31:05.498Z	WARN	livekit.transport	rtc/transport.go:1259	error reading data channel	{"room": "52341bea-4810-4950-9498-8706c60842ab", "roomID": "RM_8KDAkuUETcRE", "participant": "142601#8751b500-c0c3-11f0-b2ab-998286962dfa", "pID": "PA_h68XTimnMbVU", "remote": false, "transport": "SUBSCRIBER", "label": "_lossy", "error": "dtls timeout: read/write timeout: context deadline exceeded"}
```

**Comment by boks1971** [comment]
Thank you. Will have a look.

**Comment by boks1971** [comment]
I am not able to reproduce it. This error of read during a reconnect is possible, but it should succeed in reconnecting.

Can you reproduce using JS SDK demo app from https://github.com/livekit/client-sdk-js?tab=readme-ov-file#demo-app and share server side logs and console logs also please?

**Comment by viplifes** [comment]
Right now we rolled back to version 1.9.4, so unfortunately I cannot test this on 1.9.8 at the moment.
We also were not able to reproduce this issue on other environments, even when running 1.9.8.

However, the problem did not happen consistently.
It appeared in a room where a meeting with about 10–15 participants was supposed to take place — most people were unable to join that room at all.
At the same time, I was able to join a different empty room without any issues.
But after we reverted back to version 1.9.4, everyone was able to join that room successfully.

It might also be related to the following warning that appears when the LiveKit pod starts:
```
WARN livekit rtcconfig/rtc_unix.go:31 UDP receive buffer is too small for a production set-up {"current": 425984, "suggested": 5000000}
```

**Comment by denis-golikov** [comment]
I got same problem. In my case it was due to slow internet connection via VPN. Switch off VPN help me. I think, in some case, have a reason to play with timeouts. Total config with notation you can find here:
https://github.com/livekit/livekit/blob/master/config-sample.yaml

**Comment by boks1971** [comment]
Thank you @denis-golikov for more context.

Closing this as this does not seem to be a release related issue and not reproducible. Please re-open if this persists.

**Comment by denis-golikov** [comment]
I test this case with my friends at a distance around 7000km between us. We used wired internet without VPN. And indeed - when we start call, after several seconds it's ends with error. I think that livekit became sensetive for delay. Cause in a small distance, in the same or bordered city or region, it works perfectly.

My config for buffer size and timeouts:
```
rtc:
  packet_buffer_size_video: 5000
  packet_buffer_size_audio: 2000
signal_relay:
  retry_timeout: 30s
  min_retry_interval: 500ms
  max_retry_interval: 5s
  stream_buffer_size: 1000000
psrpc:
  timeout: 5s
  backoff: 5s
  buffer_size: 1000000
```
Nginx revers proxy have default timeouts.
